name: DreamCompass
version: "2.0"
main: io.github._7isenko.dreamcompass.DreamCompass
authors: [prosteDeni, 7isenko]
description: Gives you compass always pointing to specified player
commands:
  compass:
    description: Gives you compass always pointing to specified player
    usage: /compass <nickname>
    permission: dreamcompass.command
permissions:
  dreamcompass.command:
    description: permission to use the command
    default: true