name: DreamCompass
version: "2.1"
main: io.github._7isenko.dreamcompass.DreamCompass
author: 7isenko
description: Gives you compass always pointing to specified player
commands:
  compass:
    description: Gives you compass always pointing to specified player
    usage: /compass <nickname>
    permission: dreamcompass.command
permissions:
  dreamcompass.command:
    description: permission to use the command
    default: true