name: DreamCompass
version: 1.0
main: io.github._7isenko.dreamcompass.DreamCompass
authors: [prosteDeni, 7isenko]
description: Gives you compass always pointing to specified player
commands:
  compass:
    description: gives you a compass
    usage: /compass
